Resources:
  DjangoSecurityGroupV3:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80

  DjangoInstanceRoleV3:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  DjangoInstanceProfileV3:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref DjangoInstanceRoleV3

  DjangoEC2InstanceV3:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      IamInstanceProfile: !Ref DjangoInstanceProfileV3
      SecurityGroupIds:
        - !Ref DjangoSecurityGroupV3
      ImageId: ami-0ded8326293d3201b
