AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy EC2 for Django using existing IAM role permissions (no IAM creation)"

Parameters:
  KeyName:
    Type: String
    Description: "Name of an existing EC2 KeyPair"

Resources:

  DjangoSecurityGroupV3:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH and HTTP"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  DjangoEC2InstanceV3:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0dee22c13ea7a9a67   # Ubuntu 22.04 in ap-south-1
      SecurityGroupIds:
        - !Ref DjangoSecurityGroupV3
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          apt install -y python3-pip python3-venv git nginx
          cd /home/ubuntu
          git clone https://github.com/Sneha1016/template-django-mysql-dockercompose.git app
          cd app
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          nohup python3 manage.py runserver 0.0.0.0:80 &

Outputs:
  PublicIP:
    Description: "EC2 Public IP"
    Value: !GetAtt DjangoEC2InstanceV3.PublicIp
